import { makeStyles } from "@griffel/react"

export const useStyles = makeStyles({
    root: { display: "flex", flexDirection: "column", gap: "16px" },
    toolbar: {
        display: "flex",
        alignItems: "center",
        flexWrap: "wrap",
        gap: "10px",
    },
    search: {
        "display": "flex",
        "alignItems": "center",
        "gap": "8px",
        "flex": "1 1 220px",
        "minWidth": 0,
        "border": "1px solid var(--neutralQuaternaryAlt)",
        "borderRadius": "8px",
        "padding": "0 10px",
        "height": "36px",
        "& input": {
            width: "100%",
            minWidth: 0,
            backgroundColor: "transparent",
            border: 0,
            color: "inherit",
            font: "inherit",
            outlineStyle: "none",
        },
        ":focus-within": { outline: "2px solid var(--primary)" },
    },
    button: {
        "width": "auto",
        "minWidth": "64px",
        "height": "36px",
        "lineHeight": "36px",
        "padding": "0 12px",
        "border": "1px solid var(--neutralQuaternaryAlt)",
        "borderRadius": "8px",
        "cursor": "pointer",
        "display": "inline-flex",
        "alignItems": "center",
        "justifyContent": "center",
        "gap": "6px",
        ":focus-visible": { outline: "2px solid var(--primary)" },
    },
    primary: {
        "backgroundColor": "var(--primary)",
        "color": "white",
        "border": "1px solid var(--primary)",
        ":hover": {
            backgroundColor: "var(--primary)",
            filter: "brightness(1.08)",
        },
    },
    input: {
        "width": "100%",
        "minWidth": 0,
        "boxSizing": "border-box",
        "height": "36px",
        "padding": "0 10px",
        "border": "1px solid var(--neutralQuaternaryAlt)",
        "borderRadius": "7px",
        "backgroundColor": "var(--white)",
        "color": "var(--neutralPrimary)",
        "font": "inherit",
        ":focus-visible": { outline: "2px solid var(--primary)" },
    },
    filter: { width: "auto", maxWidth: "100%" },
    layout: {
        "display": "grid",
        "gridTemplateColumns": "minmax(230px, 0.9fr) minmax(320px, 1.3fr)",
        "gap": "20px",
        "alignItems": "start",
        "@media (max-width: 1050px)": { gridTemplateColumns: "minmax(0, 1fr)" },
    },
    list: {
        border: "1px solid var(--neutralQuaternaryAlt)",
        borderRadius: "10px",
        overflow: "hidden",
        backgroundColor: "var(--white)",
    },
    mobileHidden: { "@media (max-width: 1050px)": { display: "none" } },
    listHeader: {
        display: "flex",
        alignItems: "center",
        gap: "10px",
        padding: "12px",
        borderBottom: "1px solid var(--neutralQuaternaryAlt)",
        fontSize: "12px",
        color: "var(--neutralSecondary)",
    },
    listBody: {
        maxHeight: "calc(100vh - 290px)",
        minHeight: "280px",
        overflowY: "auto",
    },
    row: {
        "display": "flex",
        "alignItems": "center",
        "gap": "10px",
        "padding": "10px 12px",
        "borderBottom": "1px solid var(--neutralQuaternaryAlt)",
        ":last-child": { borderBottom: 0 },
        ":hover": { backgroundColor: "var(--neutralLighterAlt)" },
    },
    selected: {
        backgroundColor: "var(--neutralLight)",
        boxShadow: "3px 0 0 var(--primary) inset",
    },
    rowButton: {
        "display": "flex",
        "alignItems": "center",
        "gap": "10px",
        "flex": 1,
        "minWidth": 0,
        "padding": 0,
        "border": 0,
        "backgroundColor": "transparent",
        "color": "inherit",
        "font": "inherit",
        "textAlign": "left",
        "cursor": "pointer",
        ":focus-visible": {
            outline: "2px solid var(--primary)",
            borderRadius: "4px",
        },
    },
    icon: {
        width: "28px",
        height: "28px",
        flexShrink: 0,
        borderRadius: "6px",
        objectFit: "contain",
    },
    fallback: {
        display: "grid",
        placeItems: "center",
        backgroundColor: "var(--neutralLight)",
        fontWeight: 600,
        color: "var(--primary)",
    },
    copy: {
        "display": "flex",
        "flexDirection": "column",
        "gap": "4px",
        "minWidth": 0,
        "& strong": {
            fontSize: "13px",
            overflow: "hidden",
            textOverflow: "ellipsis",
            whiteSpace: "nowrap",
        },
    },
    hint: {
        fontSize: "12px",
        lineHeight: "18px",
        color: "var(--neutralSecondary)",
        overflowWrap: "anywhere",
    },
    metadata: {
        overflow: "hidden",
        textOverflow: "ellipsis",
        whiteSpace: "nowrap",
    },
    details: {
        "minWidth": 0,
        "border": "1px solid var(--neutralQuaternaryAlt)",
        "borderRadius": "10px",
        "backgroundColor": "var(--white)",
        "overflow": "hidden",
        "position": "sticky",
        "top": 0,
        "@media (max-width: 1050px)": { position: "static" },
    },
    heading: {
        display: "flex",
        alignItems: "center",
        gap: "10px",
        padding: "16px 18px",
        borderBottom: "1px solid var(--neutralQuaternaryAlt)",
    },
    title: {
        margin: 0,
        fontSize: "16px",
        fontWeight: 600,
        overflowWrap: "anywhere",
    },
    back: {
        "& button": { minWidth: "36px", padding: 0 },
        "@media (min-width: 1051px)": {
            display: "none",
        },
    },
    fields: {
        display: "flex",
        flexDirection: "column",
        gap: "16px",
        padding: "18px",
        border: 0,
        margin: 0,
        minWidth: 0,
        maxHeight: "calc(100vh - 360px)",
        overflowY: "auto",
    },
    field: {
        display: "flex",
        flexDirection: "column",
        gap: "6px",
        fontSize: "13px",
        minWidth: 0,
    },
    toggle: {
        display: "flex",
        alignItems: "flex-start",
        gap: "10px",
        fontSize: "13px",
        cursor: "pointer",
    },
    advanced: {
        "& summary": {
            fontSize: "13px",
            fontWeight: 600,
            cursor: "pointer",
            padding: "5px 0",
        },
        "& > div": {
            display: "flex",
            flexDirection: "column",
            gap: "14px",
            marginTop: "14px",
        },
    },
    actions: {
        display: "flex",
        justifyContent: "flex-end",
        flexWrap: "wrap",
        gap: "8px",
        padding: "14px 18px",
        borderTop: "1px solid var(--neutralQuaternaryAlt)",
    },
    danger: { color: "#c42b1c", marginRight: "auto" },
    empty: {
        padding: "32px 18px",
        color: "var(--neutralSecondary)",
        fontSize: "13px",
        textAlign: "center",
    },
})
